# Generated by Django 2.2.6 on 2020-06-13 01:32

import django.core.validators
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_freelancer_hour_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(14)]),
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, choices=[('Moscow', 'Москва'), ('SaintPetersburg', 'Санкт-Петербург'), ('Novosibirsk', 'Новосибирск'), ('Tomsk', 'Томск'), ('Tumen', 'Тюмень'), ('Barnaul', 'Барнаул'), ('Kemerovo', 'Кемерово'), ('Novokuznetsk', 'Новокузнецк'), ('Omsk', 'Омск')], max_length=25),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Мужской'), ('Female', 'Женский')], default='Не указано', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='university',
            field=models.CharField(blank=True, choices=[('Tomsk GU', 'Томский ГУ'), ('Tomsk USUR', 'ТУСУР'), ('Tomsk PT', 'Томский Политехнический'), ('Tomsk GASU', 'ТГАСУ'), ('Tomsk GPU', 'ТГПУ'), ('Nsk GU', 'Новосибирский ГУ')], max_length=25),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='technologies',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('physics', 'Физика'), ('math', 'Мат. анализ'), ('prog', 'Программирование'), ('manage', 'Менеджмент'), ('rights', 'Право')], max_length=31),
        ),
    ]
