# Generated by Django 2.2.6 on 2020-06-24 13:12

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200613_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, choices=[('Moscow', 'Москва'), ('SaintPetersburg', 'Санкт-Петербург'), ('Novosibirsk', 'Новосибирск'), ('Tomsk', 'Томск'), ('Tumen', 'Тюмень'), ('Barnaul', 'Барнаул'), ('Kemerovo', 'Кемерово'), ('Novokuznetsk', 'Новокузнецк'), ('Omsk', 'Омск')], default='Не указано', max_length=25),
        ),
        migrations.AlterField(
            model_name='profile',
            name='languages',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('be', 'Belarusian'), ('en', 'English'), ('kk', 'Kazakh'), ('ru', 'Russian'), ('uk', 'Ukrainian')], max_length=14),
        ),
        migrations.AlterField(
            model_name='profile',
            name='university',
            field=models.CharField(blank=True, choices=[('Tomsk GU', 'Томский ГУ'), ('Tomsk USUR', 'ТУСУР'), ('Tomsk PT', 'Томский Политехнический'), ('Tomsk GASU', 'ТГАСУ'), ('Tomsk GPU', 'ТГПУ'), ('Nsk GU', 'Новосибирский ГУ')], default='Не указано', max_length=25),
        ),
    ]
