# Generated by Django 2.2.6 on 2020-07-03 16:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20200702_1804'),
    ]

    operations = [
        migrations.RenameField(
            model_name='freelancer',
            old_name='universities',
            new_name='univerciies',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='university',
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='bio',
            field=models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(1000)]),
        ),
    ]
