# Generated by Django 2.2.6 on 2020-07-03 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20200703_2354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='freelancer',
            old_name='univerciies',
            new_name='univercities',
        ),
    ]
