# Generated by Django 2.2.6 on 2020-07-06 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20200706_2125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='university',
            new_name='univercity',
        ),
    ]
