# Generated by Django 2.2.6 on 2020-06-27 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_job_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='files',
            field=models.FileField(blank=True, upload_to='documents/%Y/%m/%d/'),
        ),
    ]
