# Generated by Django 2.2.6 on 2020-06-28 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_auto_20200627_1621'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SupportTicket',
        ),
    ]
