# Generated by Django 2.2.6 on 2020-07-06 11:36

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_auto_20200702_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='technologies',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('physics', 'Физика'), ('math', 'Мат. анализ'), ('prog', 'Программирование'), ('manage', 'Менеджмент'), ('rights', 'Право')], max_length=31),
        ),
    ]
