# Generated by Django 2.2.6 on 2020-07-06 14:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_auto_20200706_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='details',
            field=models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(1000)]),
        ),
    ]
