# Generated by Django 2.2.6 on 2020-07-06 15:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_auto_20200702_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='description',
            field=models.TextField(blank=True, max_length=1000, validators=[django.core.validators.MaxLengthValidator(1000)]),
        ),
    ]
